name: Pipeline Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  command-testes:
    runs-on: ubuntu-latest
    environment:
      name: ${{ contains(github.ref, 'main') && 'production' || 'other' }}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Discloud API Action - ${{ vars.ENV_NAME }} - Userinfo
        uses: marco-quicula/discloud-api-action@main
        with:
          discloud_api_token: ${{ secrets.DISCLOUD_API_TOKEN }}
          command: 'userinfo'
