name: Pipeline Tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
  workflow_dispatch:

jobs:
  command-testes:
    runs-on: ubuntu-latest
    environment:
      name: ${{ contains(github.ref, 'main') && 'production' || contains(github.ref, 'develop') && 'development' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Discloud API Action - Production - Userinfo
        if: github.ref == 'refs/heads/main'
        uses: marco-quicula/discloud-api-action@master
        with:
          discloud_api_token: ${{ secrets.DISCLOUD_API_TOKEN }}
          command: 'userinfo'
      - name: Discloud API Action - Development - Userinfo
        if: github.ref == 'refs/heads/develop'
        uses: marco-quicula/discloud-api-action@develop
        with:
          discloud_api_token: ${{ secrets.DISCLOUD_API_TOKEN }}
          command: 'userinfo'
